<?php
/*页面全局标签（顶部）-------------------------------*/
$methtml_head=metlabel_html5();//基于Html5
$metlang=metlable_lang('<span class="n-bg"></span>');//语言切换标签
$topsearch=methtml_search('0','0','','','go.gif');//顶部搜索标签
$methtml_flash=metlabel_flash();//FLASH展示标签
/*页面全局标签（底部）--------------------------------*/
$linkTi=$lang_linkName;//友情链接名称
$linkMk=$lang_linkMark;//友情链接栏目标识
$metlinkimg=methtm_link('img','com','','100','1');//图片友情链接
$metlinktxt=methtm_link('text','com','','100','1');//文字友情链接
$met_foot_nav=methtml_footnav('');//底部导航标签（次导航）
$met_foot_txt=metlabel_foot();//底部信息标签
$metonline=methtml_online();//在线交流漂浮框标签
/*---------------------------------------------------*/
if($classnow==10001){
//首页所有模块开启与关闭参数
$PublicOk=$lang_pulicOk;
$CompanyOk=$lang_companyOk;
$ProductOk=$lang_productOk;
$TownewsOk=$lang_TownewsOk;
$CaseOk=$lang_CaseOk;
$SolutionOk=$lang_SolutionOk;
$FaqOk=$lang_FaqOk;
//首页各个区块标题，调用lang目录下的语言配置文件参数
$Index_Column1=$lang_Index_Column1;
$Index_Column2=$lang_Index_Column2;
$Index_Column3=$lang_Index_Column3;
$Index_Column4=$lang_Index_Column4;
$Index_Column5=$lang_Index_Column5;
$Index_Column6=$lang_Index_Column6;
$Index_Column7=$lang_Index_Column7;
$Index_Column8=$lang_Index_Column8;
//首页各个区块栏目标识和链接
$Mark1=$lang_Index_Column1Mark;
$Mark2=$lang_Index_Column2Mark;
$Mark3=$lang_Index_Column3Mark;
$Mark4=$lang_Index_Column4Mark;
$Mark5=$lang_Index_Column5Mark;
$Mark6=$lang_Index_Column6Mark;
$Mark7=$lang_Index_Column7Mark;
$Mark8=$lang_Index_Column8Mark;
$Url1=$class_index[$Mark1]['url'];
$Url2=$class_index[$Mark2]['url'];
$Url3=$class_index[$Mark3]['url'];
$Url4=$class_index[$Mark4]['url'];
$Url5=$class_index[$Mark5]['url'];
$Url6=$class_index[$Mark6]['url'];
$Url7=$class_index[$Mark7]['url'];
$Url8=$class_index[$Mark8]['url'];
//更多
$More=$lang_Index_More;
}else{//内页标签
	$sidebar=metlabel_sidebar();//内页侧栏标签
	$sidebar_title=metlabel_sidebar(1);//内页侧栏标题
	$csnow=$cvidnow?$cvidnow:$classnow;//提交简历页面为获取到正确的页面ID，由Javascript调用
}

?>